### ISSUE TITLE
Request a full example

### ISSUE THREAD

**Issue by David-OConnor** [MichaelMauderer/filter-rs#4]
Eg with setup in `Cargo.toml`, and using `KalmanFilter` in a function or struct, so you can see how to assign the Traits. Would be much helpful.

Thank you for making this lovely port.

Eg: What do we set the traits to here? The first one appears to be the a float type of your choosing, and the others impl `nalgebra::base::dimension::DimName`, but I'm not sure what types they should be specifically.
```rust
fn create(dt: f32) -> KalmanFilter<f32, ?, ?, ?> {
    let mut kf = KalmanFilter::default();
    kf.x = Vector2::new(7.0, 0.0); // initial state (pH, and dpH_dt)
    kf.F = Matrix2::new(  // state transition matrix
        1.0, 1.0,
        0.0, 1.0,
    );
    kf.H = Vector2::new(1.0, 0.0).transpose(); // Measurement function
    kf.P *= 3.0;  // covariance matrix
    kf.R = Matrix1::new(0.01);  // state uncertainty, ie measurement noise
    kf.Q = Matrix2::repeat(STD.powi(2));
    kf
}
```

**Comment by MichaelMauderer** [comment]
The Readme does have an example that describes the types in the `Univariate Kalman Filter` section, but I agree there should be a better description in the docs and more examples. 

Essentially the three missing types describe the shape of the input and represent the size of the dimensions `X`, `Z`, and `U`. I think in your example that would result in `KalmanFilter<f32, U2, U1, U1>`. Does that help?

**Comment by David-OConnor** [comment]
Yep, that worked for me.
